require("src.core.error_handling")
require("awful.autofocus")
require("src.theme.init")
require("src.core.menu")
require("bar.init")
require("src.mappings.init")
require("src.core.rules")
require("src.core.signals")
require("src.tools.autorun")
local awful = require("awful")
awful.spawn.with_shell("~/.config/awesome/src/scripts/autorun.sh")
