require('plugins-config.lualine-config')
require('plugins-config.telescope-config')
require('plugins-config.treesitter-config')
require('plugins-config.diffview')
require('plugins-config.comment')
require('plugins-config.dap')
require('plugins-config.undotree')
require('plugins-config.nvim-tree')
